param([Parameter(Position=0)][string]$Command,[Parameter(Position=1)][string]$Project,[Parameter(Position=2)][string]$Argument,[Alias("help")][switch]$h)
$ErrorActionPreference="Stop"
$config=Get-Content (Join-Path $PSScriptRoot "config\toolkit.json") -Raw | ConvertFrom-Json
$standard=Get-Content (Join-Path $PSScriptRoot "standards\project-structure.json") -Raw | ConvertFrom-Json
$installRoot=Join-Path $env:LOCALAPPDATA "Proyecto"
$binPath=Join-Path $installRoot "bin"
$launcherPath=Join-Path $binPath "proyecto.cmd"
function Get-PryContract([string]$ProjectName){ $contractPath=Join-Path $PSScriptRoot "projects\$ProjectName\contract.json"; if(Test-Path $contractPath -PathType Leaf){ return (Get-Content $contractPath -Raw | ConvertFrom-Json) }; return $null }
function Get-PryValidation([string]$Path,[string]$ProjectName){ $lines=[System.Collections.Generic.List[string]]::new(); $missing=0; $extra=0; $contract=Get-PryContract $ProjectName; $approved=@(); if($contract -and $contract.entries){ $approved=@($contract.entries | ForEach-Object { $_.path }) }; $expected=@($standard.directories)+@($standard.files)+@("AGENTS.md","CONTEXT.md")+$approved; $standard.directories | ForEach-Object { if(Test-Path (Join-Path $Path $_) -PathType Container){ $lines.Add("[OK]    $_") }else{ $lines.Add("[FALTA] $_"); $missing++ } }; $standard.files | ForEach-Object { if(Test-Path (Join-Path $Path $_) -PathType Leaf){ $lines.Add("[OK]    $_") }else{ $lines.Add("[FALTA] $_"); $missing++ } }; $agentsPath=Join-Path $Path "AGENTS.md"; $contextPath=Join-Path $Path "CONTEXT.md"; $agentsExists=Test-Path $agentsPath -PathType Leaf; $contextExists=Test-Path $contextPath -PathType Leaf; $contextLinked=$false; if($agentsExists){ $contextLinked=(Get-Content $agentsPath -Raw) -match "(?i)CONTEXT\.md" }; if($agentsExists){ $lines.Add("[OK]    AGENTS.md") }else{ $lines.Add("[FALTA] AGENTS.md") }; if($contextExists){ $lines.Add("[OK]    CONTEXT.md") }; if(!($agentsExists -and $contextExists -and $contextLinked)){ $lines.Add("[FALTA] Integracion CONTEXT.md <-> AGENTS.md"); if($agentsExists -and !$contextExists){ $lines.Add("[PROPONE] Crear CONTEXT.md e integrarlo con AGENTS.md") }elseif(!$agentsExists -and $contextExists){ $lines.Add("[PROPONE] Crear AGENTS.md e integrarlo con CONTEXT.md") }elseif(!$agentsExists -and !$contextExists){ $lines.Add("[PROPONE] Crear e integrar AGENTS.md y CONTEXT.md") }else{ $lines.Add("[PROPONE] Integrar CONTEXT.md con AGENTS.md existente") }; $missing++ }; Get-ChildItem $Path -Force | Where-Object { $_.Name -notin $expected } | ForEach-Object { $lines.Add("[EXTRA] $($_.Name)"); $extra++ }; if($contract -and $contract.entries){ $contract.entries | ForEach-Object { if(Test-Path (Join-Path $Path $_.path)){ $lines.Add("[OK]    $($_.path) [$($_.status)]") } } }; if($missing -eq 0 -and $extra -eq 0){ $lines.Add("VALIDO - Cumple Proyecto $($standard.version)") }elseif($missing -eq 0){ $lines.Add("PENDIENTE - $extra elementos requieren adecuacion") }else{ $lines.Add("INVALIDO - Faltan $missing elementos; extras $extra elementos") }; return $lines }
if($h -or !$Command -or $Command -eq "help"){ Get-Content (Join-Path $PSScriptRoot "HELP.txt"); exit 0 }
if($Command -notin @("install","uninstall","init","valida","prompt","list","add","actualiza")){ Write-Host "Comando desconocido: $Command"; Write-Host "Use: proyecto -h"; exit 1 }
if($Command -eq "install"){ New-Item -ItemType Directory -Path $binPath -Force | Out-Null; $toolkitScript=(Join-Path $PSScriptRoot "proyecto.ps1"); "@echo off`r`npwsh.exe -NoProfile -ExecutionPolicy Bypass -File `"$toolkitScript`" %*" | Set-Content $launcherPath -Encoding ASCII; $userPath=[Environment]::GetEnvironmentVariable("Path","User"); $parts=@($userPath -split ";" | Where-Object { $_ }); if($binPath -notin $parts){ [Environment]::SetEnvironmentVariable("Path",((@($parts)+$binPath) -join ";"),"User"); Write-Host "PATH de usuario actualizado." }else{ Write-Host "PATH de usuario ya configurado." }; if($binPath -notin ($env:Path -split ";")){ $env:Path="$env:Path;$binPath" }; Write-Host "Proyecto instalado para el usuario actual."; Write-Host "Comando disponible: proyecto"; Write-Host "Launcher: $launcherPath"; exit 0 }
if($Command -eq "uninstall"){ $userPath=[Environment]::GetEnvironmentVariable("Path","User"); $parts=@($userPath -split ";" | Where-Object { $_ -and $_ -ne $binPath }); [Environment]::SetEnvironmentVariable("Path",($parts -join ";"),"User"); $env:Path=(($env:Path -split ";" | Where-Object { $_ -and $_ -ne $binPath }) -join ";"); Write-Host "Proyecto desregistrado del PATH del usuario."; Write-Host "El launcher y el toolkit NO fueron eliminados."; Write-Host "Toolkit: $PSScriptRoot"; exit 0 }
if($Command -eq "list"){ Write-Host "Componentes Proyecto:"; Write-Host "  agents"; Write-Host "  context"; Write-Host "  gitignore"; Write-Host ""; Write-Host "Skills disponibles:"; $catalog=Join-Path $PSScriptRoot "skills"; $skills=@(Get-ChildItem $catalog -Directory -ErrorAction SilentlyContinue | Where-Object { Test-Path (Join-Path $_.FullName "SKILL.md") -PathType Leaf } | Sort-Object Name); if($skills.Count -eq 0){ Write-Host "  (ninguna)" }else{ $skills | ForEach-Object { Write-Host "  $($_.Name)" } }; exit 0 }
if(!$Project){ Write-Host "Falta el nombre del proyecto."; Write-Host "Use: proyecto -h"; exit 1 }
$projectPath=Join-Path $config.projects_root $Project
if($Command -eq "init"){ if(Test-Path $projectPath){ $existing=@(Get-ChildItem $projectPath -Force); if($existing.Count -gt 0){ Write-Host "ERROR - El destino ya existe y no esta vacio: $projectPath"; exit 1 } }; New-Item -ItemType Directory -Path $projectPath -Force | Out-Null; $standard.directories | ForEach-Object { New-Item -ItemType Directory -Path (Join-Path $projectPath $_) -Force | Out-Null }; $standard.files | ForEach-Object { $f=Join-Path $projectPath $_; if(!(Test-Path $f)){ if($_ -eq ".gitignore"){ Copy-Item (Join-Path $PSScriptRoot "templates\project\.gitignore") $f }else{ New-Item -ItemType File -Path $f | Out-Null } } }; Copy-Item (Join-Path $PSScriptRoot "templates\project\AGENTS.md") (Join-Path $projectPath "AGENTS.md") -Force; Copy-Item (Join-Path $PSScriptRoot "templates\project\CONTEXT.md") (Join-Path $projectPath "CONTEXT.md") -Force; Write-Host "Proyecto Proyecto creado: $projectPath"; Write-Host "Estandar: $($standard.version)"; exit 0 }
if(!(Test-Path $projectPath -PathType Container)){ Write-Host "ERROR - Proyecto no encontrado: $projectPath"; exit 1 }
if($Command -eq "valida"){ $contextPath=Join-Path $projectPath "CONTEXT.md"; if(Test-Path $contextPath -PathType Leaf){ $context=Get-Content $contextPath -Raw; if($context -notmatch "(?im)^\*\*Estado:\*\*\s*COMPLETADO\s*$"){ $templatePath=Join-Path $PSScriptRoot "prompts\\bootstrap-proyecto.md"; if(Test-Path $templatePath -PathType Leaf){ $prompt=Get-Content $templatePath -Raw; $prompt=$prompt.Replace("{{PROJECT_NAME}}",$Project).Replace("{{PROJECT_PATH}}",$projectPath); Write-Output $prompt; exit 0 } } }; Get-PryValidation $projectPath $Project | ForEach-Object { Write-Host $_ }; exit 0 }
if($Command -eq "prompt"){ $templatePath=Join-Path $PSScriptRoot "prompts\adecuar-proyecto.md"; if(!(Test-Path $templatePath -PathType Leaf)){ Write-Host "ERROR - No se encontro la plantilla de adecuacion: $templatePath"; exit 1 }; $validationLines=@(Get-PryValidation $projectPath $Project); if($validationLines[-1] -like "VALIDO -*"){ Write-Host "Proyecto ya conforme con Proyecto $($standard.version)."; Write-Host "No se requiere prompt de adecuacion."; exit 0 }; $validation=$validationLines -join [Environment]::NewLine; $prompt=Get-Content $templatePath -Raw; $prompt=$prompt.Replace("{{PROJECT_NAME}}",$Project).Replace("{{PROJECT_PATH}}",$projectPath).Replace("{{VALIDATION_RESULT}}",$validation); Write-Output $prompt; exit 0 }
if($Command -eq "actualiza"){ $contractRoot=Join-Path $PSScriptRoot "projects\$Project"; $decisionFile=Join-Path $contractRoot "adecuacion.md"; if(!(Test-Path $decisionFile -PathType Leaf)){ Write-Host "ERROR - No se encontro la adecuacion: $decisionFile"; Write-Host "Guarde primero la respuesta revisada de la IA en esa ruta."; exit 1 }; $entries=[System.Collections.Generic.List[object]]::new(); $lineNumber=0; foreach($line in Get-Content $decisionFile){ $lineNumber++; $clean=$line.Trim(); if($clean -notmatch "^(DIR|FILE)\|"){ continue }; $parts=$clean.Split("|"); if($parts.Count -ne 3 -or $parts[0] -notin @("DIR","FILE") -or [string]::IsNullOrWhiteSpace($parts[1]) -or $parts[2] -notin @("LEGITIMO","LOCAL","SENSIBLE")){ Write-Host "ERROR - Linea $lineNumber invalida: $line"; Write-Host "No se realizaron cambios."; exit 1 }; $entries.Add([pscustomobject]@{ type=$parts[0]; path=$parts[1]; status=$parts[2] }) }; if($entries.Count -eq 0){ Write-Host "ERROR - No se encontraron decisiones DIR|... o FILE|... en: $decisionFile"; Write-Host "No se realizaron cambios."; exit 1 }; $contractPath=Join-Path $contractRoot "contract.json"; New-Item -ItemType Directory -Path $contractRoot -Force | Out-Null; [pscustomobject]@{ project=$Project; standard=$standard.version; source="adecuacion.md"; entries=@($entries) } | ConvertTo-Json -Depth 5 | Set-Content $contractPath -Encoding UTF8; Write-Host "Contrato actualizado: $contractPath"; Write-Host "Fuente: $decisionFile"; Write-Host "Decisiones registradas: $($entries.Count)"; Write-Host "El proyecto NO fue modificado."; exit 0 }
if($Command -eq "add"){ $Skill=$Argument; if(!$Skill){ Write-Host "Falta el componente o Skill."; Write-Host "Use: proyecto list"; exit 1 }; if($Skill -match "^(?i:\.?gitignore)$"){ $gitignorePath=Join-Path $projectPath ".gitignore"; if(!(Test-Path $gitignorePath -PathType Leaf)){ Copy-Item (Join-Path $PSScriptRoot "templates\project\.gitignore") $gitignorePath; Write-Host "[CREADO] .gitignore" }else{ Write-Host "[CONSERVADO] .gitignore ya existe" }; exit 0 }; if($Skill -match "^(?i:(?:agents|context))(?:\.md)?$"){ $contextPath=Join-Path $projectPath "CONTEXT.md"; $agentsPath=Join-Path $projectPath "AGENTS.md"; if(!(Test-Path $contextPath -PathType Leaf)){ Copy-Item (Join-Path $PSScriptRoot "templates\project\CONTEXT.md") $contextPath; Write-Host "[CREADO] CONTEXT.md" }else{ Write-Host "[CONSERVADO] CONTEXT.md ya existe" }; if(!(Test-Path $agentsPath -PathType Leaf)){ Copy-Item (Join-Path $PSScriptRoot "templates\project\AGENTS.md") $agentsPath; Write-Host "[CREADO] AGENTS.md" }; if((Get-Content $agentsPath -Raw) -notmatch "(?i)CONTEXT\.md"){ Add-Content $agentsPath ("`r`n"+(Get-Content (Join-Path $PSScriptRoot "templates\project\AGENTS-CONTEXT.md") -Raw)); Write-Host "[INTEGRADO] AGENTS.md -> CONTEXT.md" }else{ Write-Host "[CONSERVADO] AGENTS.md ya referencia CONTEXT.md" }; Write-Host "Integracion CONTEXT.md <-> AGENTS.md completada."; exit 0 }; $source=Join-Path $PSScriptRoot "skills\$Skill"; if(!(Test-Path $source -PathType Container)){ Write-Host "ERROR - Componente o Skill no encontrado: $Skill"; Write-Host "Use: proyecto list"; exit 1 }; if(!(Test-Path (Join-Path $source "SKILL.md") -PathType Leaf)){ Write-Host "ERROR - Skill invalida, falta SKILL.md: $Skill"; exit 1 }; $skillsRoot=Join-Path $projectPath ".agents\skills"; New-Item -ItemType Directory -Path $skillsRoot -Force | Out-Null; $destination=Join-Path $skillsRoot $Skill; if(Test-Path $destination){ Write-Host "ERROR - La Skill ya existe en el proyecto: $Skill"; exit 1 }; Copy-Item $source $destination -Recurse; Write-Host "Skill agregada: $Skill"; Write-Host "Destino: $destination"; exit 0 }

